name: contribution animation
on:
  workflow_dispatch:

permissions:
  contents: write        

jobs:
  animate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: iamRooney/contrib-blaster@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output: gif
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update contribution animation"
          file_pattern: "output/*.gif"
